services:
  # Backend Service
  - type: web
    name: fifa-match-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: fifa-match-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: client/.next
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false